### ISSUE TITLE
nlohmann JSON is not found although present, build fails (macOS, homebrew)

### ISSUE THREAD

**Issue by cpowell** [pthom/imgui_bundle_template#2]
While trying to compile the template according to the instructions on macos 15.1 and 15.2 (both tested), around 65% the following error is produced:

`/Users/chris/Desktop/imgui_bundle_template/build/_deps/imgui_bundle-src/external/immvision/immvision/src/immvision/internal/image_params_serialize.cpp:4:10: fatal error: 'nlohmann/json.hpp' file not found`

...then soon after this the build fails with `make: *** [all] Error 2`

nlohmann-json is installed via Homebrew:

```
==> nlohmann-json: stable 3.11.3 (bottled), HEAD
JSON for modern C++
https://github.com/nlohmann/json
Installed
```

And it does seem to be found by the preliminary build process:

`      nlohmann_json:                    Found via find_package(nlohmann_json)`

**Comment by pthom** [comment]
Hi,

This is fixed in https://github.com/pthom/imgui_bundle/commit/e9cdfb198d2717e6fd4553a04fd949063c42ed25

You might have to remove and recreate your build folder if imgui_bundle had been populated by cmake.
If you are using a git clone for imgui_bundle, please update it beforehand.

**Comment by cpowell** [comment]
Confirmed, build completes successfully now,. Thank you.
